// <auto-generated />
using System;
using MediaServer.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaServer.Infrastructure.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260224194222_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TvShowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TvShowId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHdr")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaylistFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("MediaProfiles");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.ToTable("SubtitleTracks");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.TvShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TvShows");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.TvShow", "TvShow")
                        .WithMany("Episodes")
                        .HasForeignKey("TvShowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TvShow");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaProfile", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.MediaItem", null)
                        .WithMany("Profiles")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.Movie", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.MediaItem", "MediaItem")
                        .WithOne("Movie")
                        .HasForeignKey("MediaServer.Domain.Entities.Movie", "MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.SubtitleTrack", b =>
                {
                    b.HasOne("MediaServer.Domain.Entities.MediaItem", null)
                        .WithMany("Subtitles")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.MediaItem", b =>
                {
                    b.Navigation("Movie");

                    b.Navigation("Profiles");

                    b.Navigation("Subtitles");
                });

            modelBuilder.Entity("MediaServer.Domain.Entities.TvShow", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
